## Multiple Linear Regression Determining p-values and Adjusted R2

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('./data/usitc/tradeVariables-mxcan.csv')
dataset.head()

year       exports       imports  travel_mx  travel_can
0  1996  5.468587e+10  7.296319e+10  276751448   153038903
1  1997  6.839322e+10  8.587234e+10  348661488   145512710
2  1998  7.536930e+10  9.470867e+10  366296614   142291790
3  1999  8.138074e+10  1.100000e+11  391959396   146497328
4  2000  1.000000e+11  1.360000e+11  392231869   147789673

In [31]:
variablesMX = dataset[["exports","imports"]].copy()
variablesMX.shape

(24, 2)

In [32]:
variablesMX.head()

exports       imports
0  5.468587e+10  7.296319e+10
1  6.839322e+10  8.587234e+10
2  7.536930e+10  9.470867e+10
3  8.138074e+10  1.100000e+11
4  1.000000e+11  1.360000e+11

In [23]:
X = dataset.iloc[:,:-2].values
y = dataset.iloc[:,3].values

In [24]:
# Building the optimal model using backward elimination
# Accounting for B0
X = np.append(arr=np.ones((24,1)).astype(int),values =X, axis =1)

In [25]:
print(X)

[[1.00000000e+00 1.99600000e+03 5.46858652e+10 7.29631894e+10]
 [1.00000000e+00 1.99700000e+03 6.83932194e+10 8.58723447e+10]
 [1.00000000e+00 1.99800000e+03 7.53693001e+10 9.47086660e+10]
 [1.00000000e+00 1.99900000e+03 8.13807402e+10 1.10000000e+11]
 [1.00000000e+00 2.00000000e+03 1.00000000e+11 1.36000000e+11]
 [1.00000000e+00 2.00100000e+03 9.05374338e+10 1.31000000e+11]
 [1.00000000e+00 2.00200000e+03 8.60760818e+10 1.35000000e+11]
 [1.00000000e+00 2.00300000e+03 8.31080960e+10 1.38000000e+11]
 [1.00000000e+00 2.00400000e+03 9.30177032e+10 1.56000000e+11]
 [1.00000000e+00 2.00500000e+03 1.02000000e+11 1.70000000e+11]
 [1.00000000e+00 2.00600000e+03 1.15000000e+11 1.98000000e+11]
 [1.00000000e+00 2.00700000e+03 1.19000000e+11 2.11000000e+11]
 [1.00000000e+00 2.00800000e+03 1.32000000e+11 2.16000000e+11]
 [1.00000000e+00 2.00900000e+03 1.06000000e+11 1.77000000e+11]
 [1.00000000e+00 2.01000000e+03 1.32000000e+11 2.30000000e+11]
 [1.00000000e+00 2.01100000e+03 1.60000000e+11 2.630000

In [26]:
X_optimzed = X[:, [0,1,2,3]]
print(X_optimzed)

[[1.00000000e+00 1.99600000e+03 5.46858652e+10 7.29631894e+10]
 [1.00000000e+00 1.99700000e+03 6.83932194e+10 8.58723447e+10]
 [1.00000000e+00 1.99800000e+03 7.53693001e+10 9.47086660e+10]
 [1.00000000e+00 1.99900000e+03 8.13807402e+10 1.10000000e+11]
 [1.00000000e+00 2.00000000e+03 1.00000000e+11 1.36000000e+11]
 [1.00000000e+00 2.00100000e+03 9.05374338e+10 1.31000000e+11]
 [1.00000000e+00 2.00200000e+03 8.60760818e+10 1.35000000e+11]
 [1.00000000e+00 2.00300000e+03 8.31080960e+10 1.38000000e+11]
 [1.00000000e+00 2.00400000e+03 9.30177032e+10 1.56000000e+11]
 [1.00000000e+00 2.00500000e+03 1.02000000e+11 1.70000000e+11]
 [1.00000000e+00 2.00600000e+03 1.15000000e+11 1.98000000e+11]
 [1.00000000e+00 2.00700000e+03 1.19000000e+11 2.11000000e+11]
 [1.00000000e+00 2.00800000e+03 1.32000000e+11 2.16000000e+11]
 [1.00000000e+00 2.00900000e+03 1.06000000e+11 1.77000000e+11]
 [1.00000000e+00 2.01000000e+03 1.32000000e+11 2.30000000e+11]
 [1.00000000e+00 2.01100000e+03 1.60000000e+11 2.630000

In [27]:
import statsmodels.api as sm

In [28]:
regressor_OLS = sm.OLS(endog = y, exog= X_optimzed).fit()

In [29]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.536
Model:                            OLS   Adj. R-squared:                  0.466
Method:                 Least Squares   F-statistic:                     7.698
Date:                Tue, 24 Mar 2020   Prob (F-statistic):            0.00130
Time:                        20:27:01   Log-Likelihood:                -450.21
No. Observations:                  24   AIC:                             908.4
Df Residuals:                      20   BIC:                             913.1
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.591e+10   1.41e+10      1.132      0.271   -1.34e+10    4.52e+10
x1          -7.79e+06   7.06e+06     -1.104      0.283   -2.25e+07    6.93e+06
x2            -0.0005      0.001     -0.493      0.627      -0.003       0.002
x3             0.0005      0.001      0.523      0.607      -0.001       0.002
==============================================================================
Omnibus:                        4.994   Durbin-Watson:                   0.418
Prob(Omnibus):                  0.082   Jarque-Bera (JB):                3.557
Skew:                          -0.935   Prob(JB):                        0.169
Kurtosis:                       3.244   Cond. No.                     4.87e+14
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.87e+14. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Fitting the linear regression model

In [38]:
X1 = variablesMX.iloc[:,:-1].values
y1 = variablesMX.iloc[:,1].values

In [40]:
print(X1.size)

24


In [39]:
print(X1)

[[5.46858652e+10]
 [6.83932194e+10]
 [7.53693001e+10]
 [8.13807402e+10]
 [1.00000000e+11]
 [9.05374338e+10]
 [8.60760818e+10]
 [8.31080960e+10]
 [9.30177032e+10]
 [1.02000000e+11]
 [1.15000000e+11]
 [1.19000000e+11]
 [1.32000000e+11]
 [1.06000000e+11]
 [1.32000000e+11]
 [1.60000000e+11]
 [1.75000000e+11]
 [1.82000000e+11]
 [1.93000000e+11]
 [1.86000000e+11]
 [1.77000000e+11]
 [1.87000000e+11]
 [2.04000000e+11]
 [1.96000000e+11]]


In [35]:
print(y1)

[7.29631894e+10 8.58723447e+10 9.47086660e+10 1.10000000e+11
 1.36000000e+11 1.31000000e+11 1.35000000e+11 1.38000000e+11
 1.56000000e+11 1.70000000e+11 1.98000000e+11 2.11000000e+11
 2.16000000e+11 1.77000000e+11 2.30000000e+11 2.63000000e+11
 2.78000000e+11 2.81000000e+11 2.96000000e+11 2.96000000e+11
 2.94000000e+11 3.13000000e+11 3.46000000e+11 3.58000000e+11]


In [41]:
# Building the optimal model using backward elimination
# Accounting for B0
X1 = np.append(arr=np.ones((24,1)).astype(int),values =X1, axis =1)
print(X1)

[[1.00000000e+00 5.46858652e+10]
 [1.00000000e+00 6.83932194e+10]
 [1.00000000e+00 7.53693001e+10]
 [1.00000000e+00 8.13807402e+10]
 [1.00000000e+00 1.00000000e+11]
 [1.00000000e+00 9.05374338e+10]
 [1.00000000e+00 8.60760818e+10]
 [1.00000000e+00 8.31080960e+10]
 [1.00000000e+00 9.30177032e+10]
 [1.00000000e+00 1.02000000e+11]
 [1.00000000e+00 1.15000000e+11]
 [1.00000000e+00 1.19000000e+11]
 [1.00000000e+00 1.32000000e+11]
 [1.00000000e+00 1.06000000e+11]
 [1.00000000e+00 1.32000000e+11]
 [1.00000000e+00 1.60000000e+11]
 [1.00000000e+00 1.75000000e+11]
 [1.00000000e+00 1.82000000e+11]
 [1.00000000e+00 1.93000000e+11]
 [1.00000000e+00 1.86000000e+11]
 [1.00000000e+00 1.77000000e+11]
 [1.00000000e+00 1.87000000e+11]
 [1.00000000e+00 2.04000000e+11]
 [1.00000000e+00 1.96000000e+11]]


In [43]:
X1_optimzed = X1
print(X1_optimzed)

[[1.00000000e+00 5.46858652e+10]
 [1.00000000e+00 6.83932194e+10]
 [1.00000000e+00 7.53693001e+10]
 [1.00000000e+00 8.13807402e+10]
 [1.00000000e+00 1.00000000e+11]
 [1.00000000e+00 9.05374338e+10]
 [1.00000000e+00 8.60760818e+10]
 [1.00000000e+00 8.31080960e+10]
 [1.00000000e+00 9.30177032e+10]
 [1.00000000e+00 1.02000000e+11]
 [1.00000000e+00 1.15000000e+11]
 [1.00000000e+00 1.19000000e+11]
 [1.00000000e+00 1.32000000e+11]
 [1.00000000e+00 1.06000000e+11]
 [1.00000000e+00 1.32000000e+11]
 [1.00000000e+00 1.60000000e+11]
 [1.00000000e+00 1.75000000e+11]
 [1.00000000e+00 1.82000000e+11]
 [1.00000000e+00 1.93000000e+11]
 [1.00000000e+00 1.86000000e+11]
 [1.00000000e+00 1.77000000e+11]
 [1.00000000e+00 1.87000000e+11]
 [1.00000000e+00 2.04000000e+11]
 [1.00000000e+00 1.96000000e+11]]


In [44]:
regressor_OLS2 = sm.OLS(endog = y, exog= X1_optimzed).fit()

In [50]:
# Running regression results
regressor_OLS2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.497
Model:                            OLS   Adj. R-squared:                  0.474
Method:                 Least Squares   F-statistic:                     21.76
Date:                Tue, 24 Mar 2020   Prob (F-statistic):           0.000119
Time:                        21:03:34   Log-Likelihood:                -451.17
No. Observations:                  24   AIC:                             906.3
Df Residuals:                      22   BIC:                             908.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.008e+08   2.21e+07     18.130      0.000    3.55e+08    4.47e+08
x1            -0.0008      0.000     -4.664      0.000      -0.001      -0.000
==============================================================================
Omnibus:                        2.222   Durbin-Watson:                   0.489
Prob(Omnibus):                  0.329   Jarque-Bera (JB):                1.442
Skew:                          -0.600   Prob(JB):                        0.486
Kurtosis:                       2.983   Cond. No.                     4.03e+11
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.03e+11. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Fitting the import, export, and travel variable

In [47]:
# Include only the import, export and travel variable
X_optimzed = X[:, [0,2,3]]
print(X_optimzed)

[[1.00000000e+00 5.46858652e+10 7.29631894e+10]
 [1.00000000e+00 6.83932194e+10 8.58723447e+10]
 [1.00000000e+00 7.53693001e+10 9.47086660e+10]
 [1.00000000e+00 8.13807402e+10 1.10000000e+11]
 [1.00000000e+00 1.00000000e+11 1.36000000e+11]
 [1.00000000e+00 9.05374338e+10 1.31000000e+11]
 [1.00000000e+00 8.60760818e+10 1.35000000e+11]
 [1.00000000e+00 8.31080960e+10 1.38000000e+11]
 [1.00000000e+00 9.30177032e+10 1.56000000e+11]
 [1.00000000e+00 1.02000000e+11 1.70000000e+11]
 [1.00000000e+00 1.15000000e+11 1.98000000e+11]
 [1.00000000e+00 1.19000000e+11 2.11000000e+11]
 [1.00000000e+00 1.32000000e+11 2.16000000e+11]
 [1.00000000e+00 1.06000000e+11 1.77000000e+11]
 [1.00000000e+00 1.32000000e+11 2.30000000e+11]
 [1.00000000e+00 1.60000000e+11 2.63000000e+11]
 [1.00000000e+00 1.75000000e+11 2.78000000e+11]
 [1.00000000e+00 1.82000000e+11 2.81000000e+11]
 [1.00000000e+00 1.93000000e+11 2.96000000e+11]
 [1.00000000e+00 1.86000000e+11 2.96000000e+11]
 [1.00000000e+00 1.77000000e+11 2.940000

In [48]:
# Refitting model without the year variable
regressor_OLS = sm.OLS(endog = y, exog= X_optimzed).fit()

In [49]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.508
Model:                            OLS   Adj. R-squared:                  0.461
Method:                 Least Squares   F-statistic:                     10.82
Date:                Tue, 24 Mar 2020   Prob (F-statistic):           0.000588
Time:                        21:02:23   Log-Likelihood:                -450.92
No. Observations:                  24   AIC:                             907.8
Df Residuals:                      21   BIC:                             911.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.931e+08   2.52e+07     15.581      0.000    3.41e+08    4.46e+08
x1            -0.0001      0.001     -0.133      0.896      -0.002       0.002
x2            -0.0004      0.001     -0.667      0.512      -0.001       0.001
==============================================================================
Omnibus:                        2.397   Durbin-Watson:                   0.443
Prob(Omnibus):                  0.302   Jarque-Bera (JB):                1.809
Skew:                          -0.664   Prob(JB):                        0.405
Kurtosis:                       2.786   Cond. No.                     8.70e+11
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.7e+11. This might indicate that there are
strong multicollinearity or other numerical problems.
"""